### ISSUE TITLE
TownyChat Incompatibility

### ISSUE THREAD

**Issue by Firav** [2lstudios-mc/ChatSentinel#11]
Attempting to use any Towny or TownyChat commands return "Wait 0.9s before sending another messsage!"

**Comment by linsaftw** [comment]
Issue from TownyChat. Ask the developer to not run commands twice and instead run the executors directly. Really bad practice from the developer.

**Comment by Firav** [comment]
I'd suggest making it known that this plugin isn't compatible with that chat system then.

**Comment by linsaftw** [comment]
> I'd suggest making it known that this plugin isn't compatible with that chat system then.

Just make an issue at the developers of Towny. I can't put all plugins that do bad practices their code it's a responsability of them.

**Comment by Firav** [comment]
[Authors response](https://github.com/TownyAdvanced/Towny/issues/5171#issuecomment-899049923) to your claims.

**Comment by linsaftw** [comment]
When this issue happens it's because a Bukkit command is run with the player as executor inside another command. This is a common issue and has been already reported by many plugins and fixed by their respective developers.
