### ISSUE TITLE
Cyrillic (Russian) support

### ISSUE THREAD

**Issue by Thin-Troll** [2lstudios-mc/ChatSentinel#13]
I would like to see Russian language support in blacklist.yml and whitelist.yml
No matter how hard I try to ban words from Russian letters, it doesn't work.
Not only that, the blacklist can be bypassed simply by mixing Cyrillic and Latin.

**Comment by Thin-Troll** [comment]
unicode ban doesn't work either

**Comment by linsaftw** [comment]
Thanks, we will try to fix this issue.

**Comment by Thin-Troll** [comment]
I don’t want to create a second issue, but I would like to see the display of the server on which the violation occurred in the plugin notification ..
 
   ` notification: "&c&lCS: &e%player% &ffailed &6Flood &7(&c%message%&7) %SERVER%"`

**Comment by linsaftw** [comment]
It would be a good idea

**Comment by linsaftw** [comment]
done
