### ISSUE TITLE
(BungeeCord) Blacklist not working with commands

### ISSUE THREAD

**Issue by elmaslarry** [2lstudios-mc/ChatSentinel#15]
The Plugin installed on bungeecord don't work as espected, It block normal chat, but if you do /msg (swear) don't block

**Comment by Gyztor** [comment]
This also happens on paper servers too when the plugin is used on both bungeecord (though i use flamecord mainly and it also appears to not be working there too) and paper. oddly shows no error at all and seems to very occasionally work with VERY certain commands though it wont happen anymore.

**Comment by linsaftw** [comment]
Is it fixed now? We did a bunch of changes.

**Comment by Gyztor** [comment]
Let me go check the new update right now :)

**Comment by Gyztor** [comment]
i tried building the plugin but still seems to be a no-go on commands in the bungeecord. should i try bungeecord (i use bungee-chat for reference) tried using /msg and it still seems to allow commands through. (this is with my configs from 0.4.2) should i try to regenerate configs first than try again? or should it not matter?

**Comment by linsaftw** [comment]
> i tried building the plugin but still seems to be a no-go on commands in the bungeecord. should i try bungeecord (i use bungee-chat for reference) tried using /msg and it still seems to allow commands through. (this is with my configs from 0.4.2) should i try to regenerate configs first than try again? or should it not matter?

It shouldn't really matter. Weird. Maybe the bungeecord commands are not allowed? Maybe try another chat plugin?

**Comment by Gyztor** [comment]
i can't use anything but bungeechat with the setup i have since it would require me to recreate from scratch but i can try on an extra bungeecord thing as a test

**Comment by linsaftw** [comment]
> i can't use anything but bungeechat with the setup i have since it would require me to recreate from scratch but i can try on an extra bungeecord thing as a test

Test server, not your main setup.

**Comment by Gyztor** [comment]
alright tested it on a clean mc server and proxy (flamecord) and the issue arises still with commands

**Comment by linsaftw** [comment]
Hmmm not sure of what causes this.

**Comment by Gyztor** [comment]
i checked and is the sever commands thing missing for the bungeecord part of the plugin (under listeners)? i tried to test copy the bukkit one and try to adapt it to the bungeecord one (it didnt work since i dont know how to code with bungeecord at all) i havent delved far into it but i noticed that wasn't there

**Comment by linsaftw** [comment]
> i checked and is the sever commands thing missing for the bungeecord part of the plugin (under listeners)? i tried to test copy the bukkit one and try to adapt it to the bungeecord one (it didnt work since i dont know how to code with bungeecord at all) i havent delved far into it but i noticed that wasn't there

It is passed through the chat listener.

**Comment by Gyztor** [comment]
woo! lets hope that is the problem

**Comment by linsaftw** [comment]
Guess what? There is no command event on bungeecord. https://github.com/SpigotMC/BungeeCord/tree/master/api/src/main/java/net/md_5/bungee/api/event

**Comment by Gyztor** [comment]
oof, okay thank you for the help :) at least we were able to figure out the issue
