### ISSUE TITLE
Flood  replace doesnt work with venturechat (Bungeecord)

### ISSUE THREAD

**Issue by TKwSni** [2lstudios-mc/ChatSentinel#17]
I was testing just for the flood control... but it doesnt do anything besides the warning... the message goes trough.

The same with the other checks, like caps

Venturechat: https://www.spigotmc.org/resources/venturechat.771/

**Comment by linsaftw** [comment]
Nothing can be done if the chat plugin or server doesn't support it. This are the only methods i have to modify the message.

**Comment by TKwSni** [comment]
Weird because bungechatfilter does work for caps filter at least while yours doesnt, maybe the listener is not catching it before sending it
