### ISSUE TITLE
ChatSentinel 0.4.4 problem

### ISSUE THREAD

**Issue by otakaros** [2lstudios-mc/ChatSentinel#19]
`Found bugs`
1. flood check - replace method not working
2. caps check - replace method not working
3. syntax check - not working
Spigot: Using latest FlamePaper & Tried on different Spigot too

Screen:
https://gyazo.com/0bf21d2ae40277a9ce3aa93bf31352d1 (flood + caps)
https://gyazo.com/ec2f53177e0d8f54c4f6fd4217cc0e90 (syntax)
- warn messages are disabled
- no bypass permission

**Comment by otakaros** [comment]
4. cooldown check - command cooldown not working

**Comment by linsaftw** [comment]
Thank you

**Comment by otakaros** [comment]
It looks like, the CAPS check is working standalone. But when is word detected by both checks at the same, then replace method is not working.
