### ISSUE TITLE
Cooldown Warn Message Error (Invalid value in %cooldown%)

### ISSUE THREAD

**Issue by artemati1** [2LStudios-MC/ChatSentinel#2]
I have ChatSentinel v0.3.8 (latest) on FlameCord server. Error is in incorrect values of the variable %cooldown% (in messages.yml).
Players receive messages like this "Please wait -8.1 seconds before use chat again." The variable %cooldown% took a negative value. And it seems like a delay in repeat and normal messages is broken (With Russian symbols, I have Russian server. Delay in normal message = delay in repeat message, when using in chat Russians symbols).

**Comment by LinsaFTW** [comment]
Hi, it will be probably fixed in the next update. Sorry for that.
