### ISSUE TITLE
Commands being caught in the filter prints the message to chat when on bungeecord.

### ISSUE THREAD

**Issue by Gyztor** [2lstudios-mc/ChatSentinel#21]
For some reason when i do /msg [username] [message sent] if there is a word setup in the black list it will print that message to main chat rather than just blocking the command or sending the message with the `***`
![image](https://user-images.githubusercontent.com/44737827/183314263-549498fb-3f4d-47fd-90a6-0cb925b759a7.png)
As you can see in the image it puts the message in main chat rather than just blocking or still running the command but with the replaced word. i am unsure if this is a bungeechat quirk but it is there
Though at least the command catching for blacklisted words works now :D

**Comment by linsaftw** [comment]
Thats because of your configuration.

**Comment by linsaftw** [comment]
Fixed in latest commit.

**Comment by linsaftw** [comment]
Nevermind. It can't be fixed. Bungee .setMessage() doesn't work.

**Comment by Gyztor** [comment]
oof, than is it possible to add a switch (specifically for commands) to cancel the command if its flagged

**Comment by Gyztor** [comment]
nvm it seems it work now
