### ISSUE TITLE
flood check problem

### ISSUE THREAD

**Issue by FairGames** [2lstudios-mc/ChatSentinel#27]
![image](https://user-images.githubusercontent.com/96260907/210381299-04f23dd3-3b5e-4b7d-9841-786dac8be68f.png)
 
 flood check problem
 if Hiiiiiiiiiiiiiiiiiiiii send only H
 
 if Helloooooooooo only Hell

**Comment by FairGames** [comment]
default pattern

**Comment by linsaftw** [comment]
Wont fix for now. Didnt find a optimized way to fix.

**Comment by FairGames** [comment]
Ok, np.
