### ISSUE TITLE
An issue showing cooldown in negative values is not fixed

### ISSUE THREAD

**Issue by artemati1** [2LStudios-MC/ChatSentinel#3]
Hello. 
I have updated the plugin to the latest version (fixing this bug), but I still get negative values in the cooldown message (the first couple of times everything worked as it should, but then it broke).
The plugin is on flamecord server.

**Comment by LinsaFTW** [comment]
That is so weird. I will keep testing to see what causes it. Thanks.

**Comment by LinsaFTW** [comment]
Hi, it seems it fixed with latest commit. I will soon upload it to SpigotMC :)
