### ISSUE TITLE
An issue showing cooldown in negative values is again not fixed (

### ISSUE THREAD

**Issue by artemati1** [2LStudios-MC/ChatSentinel#4]
Hello.
I have updated the plugin to the latest version again (fixing this bug), but I still get negative values in the cooldown message (the first couple of times everything worked as it should, but then it broke).
The plugin is on BungeeCord server.

![image](https://user-images.githubusercontent.com/49755854/93711113-3f892a80-fb54-11ea-94c4-37891b1aa66a.png)

**Comment by artemati1** [comment]
May be the reason is in Russians letters?

**Comment by LinsaFTW** [comment]
I sadly cant replicate this on my server thus can't fix it. Try with default configurations. Sorry.
