### ISSUE TITLE
An issue showing cooldown in negative values

### ISSUE THREAD

**Issue by artemati1** [2LStudios-MC/ChatSentinel#5]
You closed my previous issue #4 and told me to try using standard configurations and that this issue is not related to ChatSentinel.
However, I use the default configuration, only with modified messages and I am completely sure that the problem is in ChatSentinel. I have no other plugins interacting with the chat on BungeeCord (I have ChatSentinel installed only on BungeeCord).
I am completely sure that it's not some spigot server plugin to blame, since the message is displayed the one I specified in the ChatSentinel.

(Google Translator)

**Comment by LinsaFTW** [comment]
I am sorry but i can't follow this issue anymore because i can't replicate. If i manage to replicate it i will fix it, but while i can't replicate this will be closed because it's a dead end.
